version: "3.8"
services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: smvuser
      POSTGRES_PASSWORD: smvpass
      POSTGRES_DB: smvdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-02-02T00-00-00Z
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data

  smv_etl-pipeline:
    build: ./etl_pipeline
    depends_on:
      - minio
      - postgres
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: smv-bucket
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: smvdb
      PG_USER: smvuser
      PG_PASSWORD: smvpass
    command: ["python", "etl_script.py"]

  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./ai_model:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"

  grafana:
    image: grafana/grafana:9.0.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres

volumes:
  pgdata:
  miniodata:
  grafana_data:
